[package]
name = "shell"
version = "0.1.0"
authors = ["Maxime Desalle <hey@maxdesalle.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.121"
